"""Add company documents validation fields

Revision ID: e60a8f0c000e
Revises: 68004e4cf931
Create Date: 2026-03-19 13:56:35.951557+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e60a8f0c000e'
down_revision = '68004e4cf931'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('documents_submitted', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('companies', sa.Column('documents_validated', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('companies', sa.Column('documents_validated_at', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('documents_rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'documents_rejection_reason')
    op.drop_column('companies', 'documents_validated_at')
    op.drop_column('companies', 'documents_validated')
    op.drop_column('companies', 'documents_submitted')
    # ### end Alembic commands ###
