"""Add payment_metadata column to payments table

Revision ID: 71ce5cfb3ea4
Revises: e60a8f0c000e
Create Date: 2026-03-19 14:58:10.339946+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '71ce5cfb3ea4'
down_revision = 'e60a8f0c000e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_metadata', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'payment_metadata')
    # ### end Alembic commands ###